export const FETCH_TOEIC = "FETCH_TOEIC";
export const FETCH_TOEIC_SUCCESS = "FETCH_TOEIC_SUCCESS";
export const FETCH_TOEIC_ERROR = "FETCH_TOEIC_ERROR";

export const FETCH_TOEIC_DETAIL = "FETCH_TOEIC_DETAIL";
export const FETCH_TOEIC_DETAIL_SUCCESS = "FETCH_TOEIC_DETAIL_SUCCESS";
export const FETCH_TOEIC_DETAIL_ERROR = "FETCH_TOEIC_DETAIL_ERROR";
